title: Some words
author: Ashley Mannix
description: >-
  About Rust and open source.
baseurl: ""
url: ""
github_username:  KodrAus
mastodon:
- username: kodraus
  instance: social.kodraus.com

markdown: kramdown
theme: minima
